site_name: "AppConfiguration"
site_description: "Documentation for how to work with app registrations in Entra ID"

nav:
  - Introduction: index.md
  - Scripts:
      - CreateResourceAppRegistration: scripts/CreateResourceAppRegistration.md
      - CreateClientAppRegistration: scripts/CreateClientAppRegistration.md
      - AssignRolesToManagedIdentity: scripts/AssignRolesToManagedIdentity.md
plugins:
  - techdocs-core
markdown_extensions:
  - markdown_inline_mermaid